FROM microsoft/aspnetcore-build as builder
WORKDIR /build
COPY . .
RUN dotnet restore \
    && dotnet publish [path to Nysc.API].csproj -c release -o /build/publish
	
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
COPY --from=builder /build/publish .
EXPOSE 80/tcp
ENV ASPNETCORE_URLS http://0.0.0.0:80   
ENTRYPOINT ["dotnet", "Nysc.API.dll"]